name: avitus
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  # UI
  flutter_svg: ^1.1.6
  modal_bottom_sheet: ^2.1.2
  lottie: ^2.2.0
  pull_to_refresh: ^2.0.0
  gap: ^2.0.1
  pinput: ^2.2.16
  dotted_line: ^3.1.0
  syncfusion_flutter_sliders: ^21.1.38
  dotted_border: ^2.0.0+3
  calendar_appbar: ^0.0.6
  image_picker: ^0.8.7+2

  # Animations
  flutter_bounce: ^1.1.0
  flutter_animator: ^3.2.2
  auto_animated: ^3.1.0
  floating_action_bubble: ^1.1.4
  loading_animation_widget: ^1.2.0+4

  # Localization
  easy_localization: ^3.0.1

  # Networking
  dio: ^5.1.1
  retrofit: ^4.0.1
  connectivity_plus: ^3.0.3
  requests_inspector: ^2.3.5

  # Models
  equatable: ^2.0.5

  # State management
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1

  # Local storage
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.3

  # Firebase database
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.0
  firebase_database: ^10.1.0

  # Security
  encrypt: ^5.0.1

  # Helpers
  flutter_screenutil: ^5.6.1
  dartz: ^0.10.1
  meta: ^1.8.0
  mask_text_input_formatter: ^2.4.0
  freezed_annotation: ^2.2.0
  path_provider: ^2.0.12
  path: ^1.8.2
  url_launcher: ^6.1.9
  get_it: ^7.2.0
  intl: ^0.17.0
  xml: ^6.0.0
  dropdown_search: ^3.0.1
  flutter_rounded_date_picker: ^3.0.2
 

  # Navigation
  go_router: ^6.0.6

  # Device info
  device_info_plus: ^8.1.0
  network_info_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/translations/
    - assets/images/
    - assets/info/
  
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
